language: ruby
rvm:
  - 2.5
  - 2.6
  - jruby
  - truffleruby
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rake test
  - bundle exec rake test:system