language: ruby
services:
  - mysql
rvm:
  - 2.6.6
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'

script:
  — bundle install — jobs=3 — retry=3
  — bundle exec rake db:create
  — bundle exec rake db:migrate

notifications:
  email:
    - lna1003@naver.com

